[package]
name = "omagit-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
omagit-theme = { workspace = true }
gpui-kit = { workspace = true, features = ["assets"] }
gpui-omarchy = { workspace = true }
tracing = { workspace = true }
